twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    
    globals:
        siteTitle: '%siteTitle%'
        lang: '%lang%'
        locale: '%locale%'
        kernelRootDir: "%kernel.root_dir%"
        
    form_themes: [
      'bootstrap_4_layout.html.twig',
      '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    ]
    